# Taps
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/cask-drivers"
tap "homebrew/services"
tap "devopsdays/tap"

# Brew CLI apps
cask "google-chrome"
brew "1password-cli"
brew "awscli"
brew "azure-cli"
brew "diff-so-fancy"
brew "chezmoi"
brew "gh"
brew "git-extras"
brew "gnupg"
brew "go"
brew "hub"
brew "htop"
brew "hugo"
brew "imagemagick"
brew "jq"
brew "kubernetes-cli"
brew "mas"
brew "neovim"
brew "node"
brew "thefuck"
brew "tldr"
brew "tree"
brew "vim"
brew "wget"
brew "yadm"
brew "yarn"
brew "youtube-dl"
brew "fzf"
brew "bat"
brew "fd"
brew "ripgrep"
brew "bfg"
brew "pyenv"
brew "python@3.11"
brew "z"
cask "stats"

# App casks
cask "1password"
cask "alfred"
cask "alacritty"
cask "bartender"
cask "discord"
cask "docker"
cask 'flux'
cask "grammarly"
cask "handbrake"
cask "ngrok"
cask "notion"
cask "maccy"
cask "karabiner-elements"
cask "obsidian"
cask "postman"
cask "keepingyouawake"
cask "signal"
cask "slack"
cask "spotify"
cask "rectangle"
cask "visual-studio-code"
cask "zoom"

# Font casks
cask "font-hack-nerd-font"
cask "font-inconsolata-for-powerline"
cask "font-menlo-for-powerline"

# Mac App Store apps
mas "Spark Classic – Email App", id: 1176895641
mas "Todoist: To-Do List & Tasks", id: 585829637