[general]

import = [
  "/Users/nehiljain/.config/alacritty/catppuccin/catppuccin-frappe.toml",
]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }
size = 16.0

[terminal.shell]
program = "/opt/homebrew/bin/fish"
args = ["--login"]

[window]
padding = { x = 10, y = 10 }
dynamic_title = true
opacity = 0.90

[scrolling]
history = 100000
multiplier = 3

[bell]
animation = "EaseOutExpo"
duration = 300
color = "#ffffff"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = "Block"
unfocused_hollow = true
